export const ID_AGGLOMERATION_ROAD = 'AGGLOMERATION_ROAD';
export const ID_AGGLOMERATION_HAMLET = 'AGGLOMERATION_HAMLET';
export const ID_AGGLOMERATION_TOWN = 'AGGLOMERATION_TOWN';

export const agglomerationPiles: Array<string> = [
  ID_AGGLOMERATION_ROAD,
  ID_AGGLOMERATION_HAMLET,
  ID_AGGLOMERATION_TOWN,
];
