name: CD
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        base_href: /taormina/
        angular_dist_build_folder: docs
